const available_maps = [
	"main",
	"woffice",
	"tunnel",
	"bank",
	"cave",
	"arena",
	"tavern",
	"mansion",
	"level1",
	"hut",
	"halloween",
	"mtunnel",
	"test",
	"cyberland",
	"winterland",
	"desertland",
	"resort_e",
	"level2",
	"spookytown",
	"winter_inn",
	"winter_cave",
	"level2n",
	"level2s",
	"level3",
	"level2e",
	"level2w",
	"winter_inn_rooms",
	"level4"
];

const monsters_to_hunt = [
	"hen", "rooster", "goo", "crab", "bee", "cutebee", "minimush", "frog",
	"squigtoad", "osnake", "snake", "rat", "armadillo", "croc",
	"squig", "poisio", "snowman", "arcticbee",
	"spider", "tortoise", "bat", "goldenbat", "wabbit", "scorpion", "gscorpion",
	"iceroamer", "crabx", "bbpompom",
];

const monsters_require_focus = [
	"snowman", "scorpion", "gscorpion", "stoneworm",
	"bat", "goldenbat", "iceroamer", "crabx", "jr", "greenjr",
	"bbpompom", "booboo", "prat", "boar", "ghost", "mummy",
	"mole", "wolfie", "wolf", "xscorpion", "bigbird",
    "bat", "wabbit", "phoenix", "fvampire", "mvampire", "grinch"
];

const event_monsters = ["wabbit", "snowman"];

const special_monsters = ["cutebee", "snowman", "goldenbat", "wabbit", "phoenix", "fvampire", "mvampire", "grinch"];

const keepItems = [
	//Items
	"tracker", "computer",
	//Orbs
	"jacko", "orbg", "talkingskull",
	//Gloves
	"handofmidas", "mpgloves", "mmgloves", "mrngloves",
	//Offhands
	"lantern", "wbook1", "t2quiver",
	//Potions & Elixirs
	"hpot1", "mpot1",
	"elixirdex0", "elixirdex1", "elixirdex2",
	"elixirint0", "elixirint1", "elixirint2",
	//"elixirvit0", "elixirvit1", "elixirvit2",
	//"elixirstr0", "elixirstr1", "elixirstr2",
	"elixirluck"
];

const upgrade_items = [
	//Hunter Sets
	"mchat", "mcgloves", "mcpants", "mcarmor", "mcboots",
	"mmhat", "mmgloves", "mmpants", "mmarmor", "mmshoes",
	"mphat", "mpgloves", "mppants", "mparmor", "mpshoes",
	"mphat", "mpgloves", "mppants", "mparmor", "mpshoes",
	"mrnhat", "mrngloves", "mrnpants", "mrnarmor", "mrnboots",
];

const craft_items = [
	"rod", 
	"ctristone", 
	"firebow", 
	"frostbow", 
	"fierygloves", 
	"wingedboots", 
	"elixirdex1", 
	"elixirdex2", 
	"elixirint1", 
	"elixirint2",
	"elixirvit1", 
	"elixirvit2", 
	"xbox", 
	"basketofeggs"
];

const dismantle_items = [
	// "fireblade", "daggerofthedead", "swordofthedead", "spearofthedead", "goldenegg"
];

const items = [
// HELMETS
    "helmet",
    "wcap",
    "partyhat",
    "xmashat",
    "rednose",
    "helmet1",
    "bunnyears",
    "eears",
    "gphelmet",
    "mphat",
    "mmhat",
    "mwhelmet",
    "mrnhat",
    "mrhood",
    "mchat",
    "phelmet",
    "ghatb",
    "ghatp",
    "cyber",
    "hhelmet",
    "tigerhelmet",
    "xhelmet",
    "fury",
    "oxhelmet",

// ARMORS
    "tshirt1",
    "tshirt3",
    "tshirt8",
    "tshirt9",
    "tshirt2",
    "tshirt0",
    "tshirt7",
    "tshirt6",
    "tshirt4",
    "tshirt88",
    "coat",
    "wattire",
    "xmassweater",
    "epyjamas",
    "coat1",
    "mwarmor",
    "mrnarmor",
    "mmarmor",
    "mrarmor",
    "mcarmor",
    "mparmor",
    "luckyt",
    "sweaterhs",
    "pyjamas",
    "harmor",
    "mcape",
    "xarmor",
    "vattire",
    "cdragon",
    "warpvest",

// UNDERARMORS
    "pants",
    "wbreeches",
    "xmaspants",
    "pants1",
    "mmpants",
    "mcpants",
    "mppants",
    "mwpants",
    "mrpants",
    "mrnpants",
    "frankypants",
    "hpants",
    "fallen",
    "starkillers",
    "xpants",

// GLOVES
    "gloves",
    "wgloves",
    "poker",
    "gloves1",
    "mittens",
    "mcgloves",
    "mwgloves",
    "mpgloves",
    "mmgloves",
    "mrgloves",
    "mrngloves",
    "fierygloves",
    "hgloves",
    "vgloves",
    "supermittens",
    "handofmidas",
    "powerglove",
    "xgloves",
    "goldenpowerglove",
    "mpxgloves",

// SHOES
    "shoes",
    "eslippers",
    "wshoes",
    "xmasshoes",
    "shoes1",
    "wingedboots",
    "mcboots",
    "mmshoes",
    "mrboots",
    "mpshoes",
    "mrnboots",
    "mwboots",
    "vboots",
    "snowboots",
    "iceskates",
    "hboots",
    "xboots",

// CAPES
    "gcape",
    "cape",
    "ecape",
    "angelwings",
    "vcape",
    "stealthcape",
    "bcape",
    "tigercape",
    "fcape",

// RINGS
    "dexring",
    "ringsj",
    "intring",
    "vitring",
    "strring",
    "cdarktristone",
    "ctristone",
    "armorring",
    "resistancering",
    "cring",
    "solitaire",
    "suckerpunch",
    "vring",
    "zapper",
    "ringofluck",
    "trigger",
    "ringhs",
    "goldring",

// EARRINGS
    "strearring",
    "dexearring",
    "intearring",
    "vitearring",
    "dexearringx",
    "lostearring",
    "cearring",
    "molesteeth",
    "mearring",

// AMULETS
    "hpamulet",
    "warmscarf",
    "dexamulet",
    "skullamulet",
    "intamulet",
    "stramulet",
    "t2dexamulet",
    "t2stramulet",
    "t2intamulet",
    "spookyamulet",
    "snring",
    "bfangamulet",
    "amuletofm",
    "sanguine",
    "mpxamulet",
    "northstar",

// BELTS
    "hpbelt",
    "lbelt",
    "dexbelt",
    "strbelt",
    "intbelt",
    "mbelt",
    "santasbelt",
    "sbelt",
    "mpxbelt",

// ORBS
    "test_orb",
    "orbg",
    "jacko",
    "ftrinket",
    "talkingskull",
    "rabbitsfoot",
    "charmer",
    "orbofsc",
    "orbofdex",
    "orbofint",
    "orbofvit",
    "orbofstr",
    "tigerstone",
    "vorb",

// WEAPONS
    "broom",
    "mace",
    "wbasher",
    "claw",
    "blade",
    "cclaw",
    "staff",
    "stinger",
    "hbow",
    "bow",
    "glolipop",
    "ololipop",
    "mushroomstaff",
    "slimestaff",
    "pouchbow",
    "weaver",
    "xmace",
    "sword",
    "swifty",
    "wand",
    "throwingstars",
    "fclaw",
    "spear",
    "candycanesword",
    "fsword",
    "basher",
    "frostbow",
    "t2bow",
    "rapier",
    "pmace",
    "cupid",
    "snowflakes",
    "carrotsword",
    "fireblade",
    "ornamentstaff",
    "merry",
    "bataxe",
    "pinkie",
    "dagger",
    "firebow",
    "firestaff",
    "swordofthedead",
    "daggerofthedead",
    "woodensword",
    "maceofthedead",
    "staffofthedead",
    "bowofthedead",
    "harbringer",
    "oozingterror",
    "froststaff",
    "firestars",
    "crossbow",
    "spearofthedead",
    "harpybow",
    "t3bow",
    "pmaceofthedead",
    "lmace",
    "hammer",
    "gstaff",
    "hdagger",
    "dragondagger",
    "gbow",
    "scythe",
    "vsword",
    "vdagger",
    "vstaff",
    "vhammer",
    "heartwood",
    "dartgun",
    "wblade",

// SHILDS
    "wshield",
    "shield",
    "sshield",
    "tigershield",
    "xshield",
    "mshield",

// OFFHANDS
    "wbook0",
    "quiver",
    "lantern",
    "wbookhs",
    "wbook1",
    "t2quiver",
    "exoarm",

// ELIXIRS
    "xshot",
    "gum",
    "cake",
    "candypop",
    "pumpkinspice",
    "elixirstr0",
    "elixirint0",
    "eggnog",
    "elixirvit0",
    "elixirdex0",
    "bunnyelixir",
    "hotchocolate",
    "greenbomb",
    "swirlipop",
    "espresso",
    "elixirvit1",
    "elixirstr1",
    "elixirdex1",
    "elixirint1",
    "ale",
    "wine",
    "whiskey",
    "elixirvit2",
    "elixirstr2",
    "elixirdex2",
    "elixirint2",
    "blue",
    "pico",
    "vblood",
    "elixirpnres",
    "elixirluck",
    "elixirfzres",
    "elixirfires",

// POTIONS
    "hpot0",
    "mpot0",
    "hpot1",
    "mpot1",
    "snakeoil",
    "hpotx",
    "mpotx",

// SCROLLS
    "scroll0",
    "cscroll0",
    "evasionscroll",
    "outputscroll",
    "strscroll",
    "critscroll",
    "goldscroll",
    "lifestealscroll",
    "forscroll",
    "intscroll",
    "apiercingscroll",
    "armorscroll",
    "resistancescroll",
    "mpcostscroll",
    "xpscroll",
    "reflectionscroll",
    "manastealscroll",
    "frequencyscroll",
    "rpiercingscroll",
    "dreturnscroll",
    "vitscroll",
    "speedscroll",
    "dexscroll",
    "luckscroll",
    "scroll1",
    "cscroll1",
    "offeringp",
    "scroll2",
    "cscroll2",
    "offering",
    "offeringx",
    "scroll3",
    "scroll4",
    "cscroll3",

// Crafting and Collecting
    "essenceoflife",
    "rattail",
    "frogt",
    "carrot",
    "pstem",
    "whiteegg",
    "bfur",
    "electronics",
    "essenceofgreed",
    "mbones",
    "gslime",
    "beewings",
    "bandages",
    "rfur",
    "smush",
    "dstones",
    "crabclaw",
    "bwing",
    "spores",
    "lspores",
    "cscale",
    "cocoon",
    "spidersilk",
    "pleather",
    "drapes",
    "ascale",
    "feather0",
    "feather1",
    "brownegg",
    "snakefang",
    "tshell",
    "bronzenugget",
    "sstinger",
    "essenceofnature",
    "ink",
    "lotusf",
    "emptyheart",
    "rfangs",
    "svenom",
    "bfang",
    "cshell",
    "essenceoffire",
    "bronzeingot",
    "essenceofether",
    "essenceoffrost",
    "btusk",
    "ectoplasm",
    "goldnugget",
    "trinkets",
    "ijx",
    "bcandle",
    "watercore",
    "goldingot",
    "platinumnugget",
    "nheart",
    "networkcard",
    "platinumingot",

// Exchangeables
    "5bucks",
    "gift1",
    "seashell",
    "gift0",
    "leather",
    "ornament",
    "troll",
    "basketofeggs",
    "mistletoe",
    "candycane",
    "candy1",
    "gem1",
    "greenenvelope",
    "redenvelopev2",
    "redenvelopev3",
    "redenvelopev4",
    "redenvelope",
    "gemfragment",
    "goldenegg",
    "armorbox",
    "bugbountybox",
    "candy0",
    "gem0",
    "weaponbox",
    "xbox",
    "cosmo2",
    "cosmo0",
    "mysterybox",
    "cosmo3",

// KEYS
    "frozenkey",
    "cryptkey",
    "stonekey",
    "tombkey",
    "bkey",
    "ukey",
    "dkey",

// OTHERS
    "emptyjar",
    "cxjar",
    "snowball",
    "emotionjar",
    "coal",
    "tracker",
    "confetti",
    "smoke",
    "firecrackers",
    "shadowstone",
    "poison",
    "rod",
    "pickaxe",
    "x2",
    "x0",
    "x7",
    "x5",
    "egg3",
    "egg5",
    "egg0",
    "egg2",
    "egg4",
    "egg6",
    "x3",
    "x1",
    "x6",
    "x4",
    "egg8",
    "egg1",
    "egg7",
    "x8",
    "puppyer",
    "funtoken",
    "monstertoken",
    "frozenstone",
    "pvptoken",
    "friendtoken",
    "stand0",
    "stick",
    "gem2",
    "fieldgen0",
    "xptome",
    "gem3",
    "qubics",
    "bottleofxp",
    "cosmo1",
    "licence",
    "cosmo4",
    "supercomputer",
    "computer",
    "goldbooster",
    "xpbooster",
    "luckbooster",
    "flute",
]

const trash_items = [
    // HELMETS
        "helmet",
        "wcap",
        "partyhat",
        "xmashat",
        "rednose",
        "helmet1",
        "bunnyears",
        "eears",
        // "gphelmet",
        // "mphat",
        // "mmhat",
        // "mwhelmet",
        // "mrnhat",
        // "mrhood",
        // "mchat",
        // "phelmet",
        "ghatb",
        "ghatp",
        // "cyber",
        // "hhelmet",
        // "tigerhelmet",
        // "xhelmet",
        // "fury",
        // "oxhelmet",
    
    // ARMORS
        // "tshirt1",
        // "tshirt3",
        // "tshirt8",
        // "tshirt9",
        // "tshirt2",
        // "tshirt0",
        // "tshirt7",
        // "tshirt6",
        // "tshirt4",
        // "tshirt88",
        "coat",
        "wattire",
        "xmassweater",
        "epyjamas",
        "coat1",
        // "mwarmor",
        // "mrnarmor",
        // "mmarmor",
        // "mrarmor",
        // "mcarmor",
        // "mparmor",
        // "luckyt",
        "sweaterhs",
        "pyjamas",
        "harmor",
        // "mcape",
        // "xarmor",
        // "vattire",
        // "cdragon",
        // "warpvest",
    
    // UNDERARMORS
        "pants",
        "wbreeches",
        "xmaspants",
        "pants1",
        // "mmpants",
        // "mcpants",
        // "mppants",
        // "mwpants",
        // "mrpants",
        // "mrnpants",
        // "frankypants",
        "hpants",
        // "fallen",
        // "starkillers",
        // "xpants",
    
    // GLOVES
        "gloves",
        "wgloves",
        "poker",
        "gloves1",
        "mittens",
        // "mcgloves",
        // "mwgloves",
        // "mpgloves",
        // "mmgloves",
        // "mrgloves",
        // "mrngloves",
        // "fierygloves",
        "hgloves",
        // "vgloves",
        // "supermittens",
        // "handofmidas",
        // "powerglove",
        // "xgloves",
        // "goldenpowerglove",
        // "mpxgloves",
    
    // SHOES
        "shoes",
        "eslippers",
        "wshoes",
        "xmasshoes",
        "shoes1",
        // "wingedboots",
        // "mcboots",
        // "mmshoes",
        // "mrboots",
        // "mpshoes",
        // "mrnboots",
        // "mwboots",
        // "vboots",
        // "snowboots",
        "iceskates",
        "hboots",
        // "xboots",
    
    // CAPES
        // "gcape",
        // "cape",
        // "ecape",
        // "angelwings",
        // "vcape",
        // "stealthcape",
        // "bcape",
        // "tigercape",
        // "fcape",
    
    // RINGS
        // "dexring",
        // "ringsj",
        // "intring",
        // "vitring",
        // "strring",
        // "cdarktristone",
        // "ctristone",
        // "armorring",
        // "resistancering",
        // "cring",
        // "solitaire",
        // "suckerpunch",
        // "vring",
        // "zapper",
        // "ringofluck",
        // "trigger",
        // "ringhs",
        // "goldring",
    
    // EARRINGS
        // "strearring",
        // "dexearring",
        // "intearring",
        // "vitearring",
        // "dexearringx",
        // "lostearring",
        // "cearring",
        // "molesteeth",
        // "mearring",
    
    // AMULETS
        // "hpamulet",
        // "warmscarf",
        // "dexamulet",
        // "skullamulet",
        // "intamulet",
        // "stramulet",
        // "t2dexamulet",
        // "t2stramulet",
        // "t2intamulet",
        // "spookyamulet",
        // "snring",
        // "bfangamulet",
        // "amuletofm",
        // "sanguine",
        // "mpxamulet",
        // "northstar",
    
    // BELTS
        // "hpbelt",
        // "lbelt",
        // "dexbelt",
        // "strbelt",
        // "intbelt",
        // "mbelt",
        // "santasbelt",
        // "sbelt",
        // "mpxbelt",
    
    // ORBS
        // "test_orb",
        // "orbg",
        // "jacko",
        // "ftrinket",
        // "talkingskull",
        // "rabbitsfoot",
        // "charmer",
        // "orbofsc",
        // "orbofdex",
        // "orbofint",
        // "orbofvit",
        // "orbofstr",
        // "tigerstone",
        // "vorb",
    
    // WEAPONS
        "broom",
        "mace",
        "wbasher",
        "claw",
        "blade",
        "cclaw",
        // "staff",
        "stinger",
        // "hbow",
        "bow",
        "glolipop",
        "ololipop",
        "mushroomstaff",
        "slimestaff",
        "pouchbow",
        "weaver",
        "xmace",
        "sword",
        "swifty",
        "wand",
        "throwingstars",
        // "fclaw",
        "spear",
        "candycanesword",
        // "fsword",
        "basher",
        // "frostbow",
        // "t2bow",
        "rapier",
        "pmace",
        "cupid",
        "snowflakes",
        "carrotsword",
        // "fireblade",
        "ornamentstaff",
        "merry",
        "bataxe",
        "pinkie",
        "dagger",
        // "firebow",
        // "firestaff",
        "swordofthedead",
        "daggerofthedead",
        // "woodensword",
        "maceofthedead",
        "staffofthedead",
        "bowofthedead",
        // "harbringer",
        // "oozingterror",
        // "froststaff",
        // "firestars",
        "crossbow",
        // "spearofthedead",
        // "harpybow",
        // "t3bow",
        "pmaceofthedead",
        // "lmace",
        // "hammer",
        // "gstaff",
        // "hdagger",
        // "dragondagger",
        // "gbow",
        // "scythe",
        // "vsword",
        // "vdagger",
        // "vstaff",
        // "vhammer",
        // "heartwood",
        // "dartgun",
        // "wblade",
    
    // SHILDS
        "wshield",
        // "shield",
        // "sshield",
        // "tigershield",
        // "xshield",
        // "mshield",
    
    // OFFHANDS
        "wbook0",
        // "quiver",
        // "lantern",
        // "wbookhs",
        // "wbook1",
        // "t2quiver",
        // "exoarm",
    
    // ELIXIRS
        // "xshot",
        // "gum",
        // "cake",
        // "candypop",
        // "pumpkinspice",
        // "elixirstr0",
        // "elixirint0",
        // "eggnog",
        // "elixirvit0",
        // "elixirdex0",
        // "bunnyelixir",
        // "hotchocolate",
        // "greenbomb",
        // "swirlipop",
        // "espresso",
        // "elixirvit1",
        // "elixirstr1",
        // "elixirdex1",
        // "elixirint1",
        // "ale",
        // "wine",
        // "whiskey",
        // "elixirvit2",
        // "elixirstr2",
        // "elixirdex2",
        // "elixirint2",
        // "blue",
        // "pico",
        // "vblood",
        // "elixirpnres",
        // "elixirluck",
        // "elixirfzres",
        // "elixirfires",
    
    // POTIONS
        "hpot0",
        "mpot0",
        // "hpot1",
        // "mpot1",
        // "snakeoil",
        // "hpotx",
        // "mpotx",
    
    // SCROLLS
        "scroll0",
        "cscroll0",
        // "evasionscroll",
        // "outputscroll",
        // "strscroll",
        // "critscroll",
        // "goldscroll",
        // "lifestealscroll",
        // "forscroll",
        // "intscroll",
        // "apiercingscroll",
        // "armorscroll",
        // "resistancescroll",
        // "mpcostscroll",
        // "xpscroll",
        // "reflectionscroll",
        // "manastealscroll",
        // "frequencyscroll",
        // "rpiercingscroll",
        // "dreturnscroll",
        // "vitscroll",
        // "speedscroll",
        // "dexscroll",
        // "luckscroll",
        // "scroll1",
        // "cscroll1",
        // "offeringp",
        // "scroll2",
        // "cscroll2",
        // "offering",
        // "offeringx",
        // "scroll3",
        // "scroll4",
        // "cscroll3",
    
    // Crafting and Collecting
        // "essenceoflife",
        // "rattail",
        // "frogt",
        // "carrot",
        // "pstem",
        // "whiteegg",
        // "bfur",
        // "electronics",
        // "essenceofgreed",
        // "mbones",
        // "gslime",
        // "beewings",
        // "bandages",
        // "rfur",
        // "smush",
        // "dstones",
        // "crabclaw",
        // "bwing",
        // "spores",
        // "lspores",
        // "cscale",
        // "cocoon",
        // "spidersilk",
        // "pleather",
        // "drapes",
        // "ascale",
        // "feather0",
        // "feather1",
        // "brownegg",
        // "snakefang",
        // "tshell",
        // "bronzenugget",
        // "sstinger",
        // "essenceofnature",
        // "ink",
        // "lotusf",
        // "emptyheart",
        // "rfangs",
        // "svenom",
        // "bfang",
        // "cshell",
        // "essenceoffire",
        // "bronzeingot",
        // "essenceofether",
        // "essenceoffrost",
        // "btusk",
        // "ectoplasm",
        // "goldnugget",
        // "trinkets",
        // "ijx",
        // "bcandle",
        // "watercore",
        // "goldingot",
        // "platinumnugget",
        // "nheart",
        // "networkcard",
        // "platinumingot",
    
    // Exchangeables
        // "5bucks",
        // "gift1",
        // "seashell",
        // "gift0",
        // "leather",
        // "ornament",
        // "troll",
        // "basketofeggs",
        // "mistletoe",
        // "candycane",
        // "candy1",
        // "gem1",
        // "greenenvelope",
        // "redenvelopev2",
        // "redenvelopev3",
        // "redenvelopev4",
        // "redenvelope",
        // "gemfragment",
        // "goldenegg",
        // "armorbox",
        // "bugbountybox",
        // "candy0",
        // "gem0",
        // "weaponbox",
        // "xbox",
        // "cosmo2",
        // "cosmo0",
        // "mysterybox",
        // "cosmo3",
    
    // KEYS
        // "frozenkey",
        // "cryptkey",
        // "stonekey",
        // "tombkey",
        // "bkey",
        // "ukey",
        // "dkey",
    
    // OTHERS
        // "emptyjar",
        // "cxjar",
        // "snowball",
        // "emotionjar",
        // "coal",
        // "tracker",
        // "confetti",
        // "smoke",
        // "firecrackers",
        // "shadowstone",
        // "poison",
        // "rod",
        // "pickaxe",
        // "x2",
        // "x0",
        // "x7",
        // "x5",
        // "egg3",
        // "egg5",
        // "egg0",
        // "egg2",
        // "egg4",
        // "egg6",
        // "x3",
        // "x1",
        // "x6",
        // "x4",
        // "egg8",
        // "egg1",
        // "egg7",
        // "x8",
        // "puppyer",
        // "funtoken",
        // "monstertoken",
        // "frozenstone",
        // "pvptoken",
        // "friendtoken",
        // "stand0",
        // "stick",
        // "gem2",
        // "fieldgen0",
        // "xptome",
        // "gem3",
        // "qubics",
        // "bottleofxp",
        // "cosmo1",
        // "licence",
        // "cosmo4",
        // "supercomputer",
        // "computer",
        // "goldbooster",
        // "xpbooster",
        // "luckbooster",
        // "flute",
]

